### ISSUE TITLE
Redirecting to index.html on refresh

### ISSUE THREAD

**Issue by agyin3** [Lambda-School-Labs/lets-get-pizza-fe#68]
On the deployed app whenever you refresh a page it automatically redirects you to `/index.html` and renders the 404 not found page

**Comment by jchaing** [comment]
I did see the 404 error message one time yesterday. Today, I'm not able to replicate the error.

**Comment by agyin3** [comment]
Was able to find these [docs](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa) on the AWS website and it looks to have solved the issue. Will be closing now
